<div class="terms">
  <span class="close">Close</span>
  <h1>Terms of Service</h1>
  <h3>Effective Date: September 17, 2013</h3>
  <div>
    <p>This agreement was written in English (USA). To the extent any translated version of this agreement conflicts with the English version, the English version prevails and controls.  Please note that Section(s) 12.0 and 19.0 contain certain changes to the general terms for users outside the United States.</p>
    
    <p>EarDish Corp, ("We/Us") a duly formed Delaware corporation, owns and operates the EarDish Corp website and provides all related EarDish Corp tools and services. By using this Web Site (the &quot;Service&quot;), you (&quot;you&quot; or the &quot;End User&quot;) must agree to each of the terms and conditions contained in this Terms and Conditions Document.</p>

    <p>THESE TERMS CREATE A BINDING LEGAL CONTRACT BETWEEN YOU AND EARDISH, Corporation (&quot;<strong>EarDish</strong>&quot;). YOUR ACCESS TO AND USE OF THE EARDISH.COM WEB SITE (THE "SERVICE"), IS SUBJECT TO YOUR AGREEMENT TO THE TERMS AND CONDITIONS LISTED BELOW, WHICH WILL BECOME A BINDING AGREEMENT BETWEEN YOU AND THE COMPANY (THE "AGREEMENT"). THE COMPANY IS WILLING TO ALLOW YOU ACCESS TO THE SERVICE ONLY UPON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS OF THIS AGREEMENT.</p>

    <p>PLEASE READ THESE TERMS CAREFULLY. AFTER READING THE TERMS. BY USING THE SERVICE, WHETHER AS A FAN, ARTIST OR ANY OTHER PROFILE PROVIDED UNDER THIS SERVICE, YOU REPRESENT AND WARRANT THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT ACCEPT THESE TERMS, YOU MUST NOT USE, AND ARE NOT AUTHORIZED TO USE, ALL OR ANY PORTION OF THE SERVICE.</p>

    <p><strong>IF YOU AGREE TO THEM, PLEASE INDICATE YOUR DECISION BY CLICKING ON "I AGREE" AT THE END OF THIS AGREEMENT.</strong></p>

    <p><strong>IF YOU DO NOT AGREE, INDICATE YOUR DECISION BY CLICKING ON "I DO NOT AGREE" AND YOU WILL BE RETURNED TO THE HOME PAGE OF THIS WEB SITE.</strong></p>

    <h3>OVERVIEW</h3>

    <p>Welcome to EarDish, an artist discovery and development community!  EarDish provides artist development, artist funding and promotional services at no charge to artists, fans and music industry professionals.  All of our various promotional services are provided at no cost to our members.  We will never own the copyrights to any songs that your own or any provided to us for promotional purposes.  We will also not own any interest in your trademarks, images, text or other elements of intellectual property but we will ask your permission to use the same strictly for the purpose of providing you with free promotional services. Artists will be eligible to earn income from activity-based financial rewards in a manner truly unique to other businesses that provide to artists. We require no recording contracts or recoupment methods to artists who receive funding directly from the EarDish service. All Artist Development funds are available to any artist and you earn eligibility to these funds by growing your Fan base through song ratings and popularity. We are non-exclusive, so Artists may add or remove their songs from EarDish whenever they would like.</p>

    <p><strong>1.0 REGISTRATION.</strong> In order to gain access to the services (the "Services") offered by the Web Site, you will need to register as a user. Either you or the Company may terminate your user registration at any time. Upon termination of your registration as a "user", you will no longer be allowed access to the Web Site or the Services offered through the Web Site. You represent that all information you provide during the registration process and at any time thereafter ("Registration Information") will be true, accurate, complete, and current and that you will promptly update your Registration Information as necessary such that it is, at all times, true, accurate, complete, and current. The Company may use all Registration Information, subject to Company's compliance with the Company Privacy Policy that can be found here, www.eardish.com/privacy (the "Privacy Policy").</p>

      <p><em>This Agreement includes terms and conditions set forth in the Privacy Policy. By indicating your agreement to this Agreement, you are consenting to have your personal data used by the Company as set forth in the Privacy Policy.</em></p>

    <p><strong>1.1 REGISTERING ENTITY.</strong>  If you are using or opening an account on the Service on behalf of a company, entity or organization (including, but not limited to, an Artist/Band, Business, Charity, Industry Professional or any other Profile) (each a &quot;Registering Entity&quot;), then you represent and warrant that you:</p>

    <p>a)  Are an authorized representative of that Registering Entity with the authority to bind such entity to these Terms and</p>

    <p>b)  Agree to be bound by these Terms on behalf of such Registering Entity.</p>

    <p><strong>1.2 MODIFICATION OF TERMS.</strong> The Website and portions of the Service are owned and operated by EarDish, which reserves the right to revise these Terms in its sole discretion at any time and without prior notice to you other than by posting the revised Terms on the Website. Any revisions to the Terms are effective upon posting. The Terms will be identified as of the most recent date of revision. It is incumbent upon you to visit this page periodically to ensure your continued acceptance of these Terms. Your continued use of the Service after any revised version of these Terms has been posted by EarDish to the Website, constitutes your binding acceptance of such revision and the revised Terms.</p>

    <p>Notwithstanding the preceding sentences of this Section 1.2, no revisions to these Terms will apply to any dispute between you and EarDish that arose prior to the date of such revision.</p>

    <p><strong>1.3 CONSIDERATION.</strong> You understand and agree that these Terms are entered into in consideration of your use of the Service and other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged.</p>

    <p><strong>1.4 CHANGES TO THIS SERVICE.</strong> The Service is continually under development and changes to the Service may be made at any time. If you disagree with the Terms or are in any way dissatisfied with the Service, your sole remedy is to discontinue your use of the Service.</p>

    <p><strong>2.0 UPLOADING CONTENT.</strong>  This section governs any material that you upload or transmit to or through the Service or to us through email outside of a Forum, including, without limitation, musical works, sound recordings, literary works, photographs, audiovisual works, artwork, comments, information regarding commerce offerings listed on the Service, and messages (collectively, &quot;<strong>User Content</strong>&quot;).</p>

    <p>To be perfectly clear, this includes User Content that may be uploaded to and/or accessed from third-party sites that may host all or any portion of your User Content, such as, by way of example and not limitation Facebook, YouTube, Vimeo, and SoundCloud (each a &quot;<strong>Hosting Service</strong>&quot; and, collectively, the &quot;<strong>Hosting Services</strong>&quot;).</p>

    <p>You are solely responsible for all User Content you submit to or through the Service, including sound recordings (and any musical works embodied therein) transmitted by you through the Service to any Hosting Services. You agree, represent, and warrant that any User Content you upload or transmit to or through the Service or to us through email is truthful, accurate, not misleading, and offered in good faith, and that you have all rights, licenses, permissions, and authorizations necessary to upload and transmit the User Content to and through the Service and grant the rights to the User Content as set forth in these Terms.</p> 

    <p>You must not upload or transmit any User Content to or through the Service or to us through email that you consider to be confidential or proprietary or the rights to which have not been cleared by you. Except as otherwise expressly agreed to in a separate writing signed by you and an authorized representative of EarDish, or as otherwise specified in these Terms, any User Content uploaded or transmitted to or through the Service or to us via email will be considered non-confidential and non-proprietary, and treated as such by EarDish, and may be used by EarDish for any purpose or disclosed by EarDish to any third party with or without notice to you and without any liability to EarDish.</p>

    <p><strong>2.1 RETENTION OF YOUR INTELLECTUAL PROPERTY RIGHTS.</strong> <em>BY UPLOADING OR OTHERWISE PROVIDING USER CONTENT TO THE SERVICE YOU ARE NOT, PURSUANT TO THESE TERMS, SURRENDERING ANY INTELLECTUAL PROPERTY RIGHTS IN YOUR USER CONTENT THAT YOU MAY HAVE. RATHER, YOU ARE MERELY GRANTING EARDISH A LICENSE PURSUANT TO THE PROVISIONS OF THESE TERMS. YOU WILL CONTINUE TO OWN, TO THE EXTENT OF YOUR EXISTING RIGHTS, ALL OF YOUR USER CONTENT, INCLUDING, BUT NOT LIMITED TO, YOUR SOUND RECORDINGS, MUSICAL WORKS, AND AUDIOVISUAL WORKS. NOTWITHSTANDING THE PRECEDING SENTENCES OF THIS SECTION 8.1, ANY USER CONTENT TRANSMITTED BY YOU THROUGH THE SERVICE TO ANY HOSTING SERVICES OR OTHER THIRD PARTY, SUCH AS, BY WAY OF EXAMPLE AND NOT LIMITATION, SOUNDCLOUD, WILL BE SUBJECT TO THE TERMS OF USE OR SERVICE OF SUCH HOSTING SERVICES OR OTHER THIRD PARTY, INCLUDING, BUT NOT LIMITED TO, THE GRANT OF RIGHTS GIVEN BY YOU TO SUCH HOSTING SERVICES OR OTHER THIRD PARTY WITH RESPECT TO YOUR USER CONTENT, IF ANY.</em></p>

    <p><strong>2.2 NO COMMERCIAL RIGHTS TO SELL.</strong> This section shall confirm that at <strong>>no time will</strong> either <strong>EarDish or any user have any rights to sell</strong> or commercialize <strong>your music</strong>. When you publish a music file to the Web Site, <strong>you make the file available for Listening and Playback ONLY</strong>. Therefore, users can only listen to the music file. <strong>No other rights are transferred</strong> to us or to any users. We cannot sell or distribute the music file, or make it available for any commercial purpose without your permission. The only thing we can do with the music file is to allow users to play it within our service or inside of future applications that become available from our service (and third party providers). Although the user can play the file, the user cannot sell, distribute or commercialize the music file in any way or use it for any commercial purposes and you still retain all rights to commercialize your music.</p>

    <p><strong>2.3 LICENSE TO CONTENT.</strong> By Publishing Content to any part of the Web Site, you automatically grant to the Company, and you represent and warrant that you have the right to grant to the Company, a non-exclusive, transferable, fully-paid, worldwide license (with the rights to sub-license) to use, copy, perform, display, reformat, translate, excerpt (in whole or in part) and distribute such Content and to prepare derivative works of, or incorporate into other works, such Content, and to grant and authorize sub-licenses of the foregoing. This license includes without limitation any and all professional names, photos, trademarks, logos and biographical information of artists, performers or bands. You may remove such Content from this service at any time and the license granted above will automatically terminate.</p>

    <p><strong>THE FOREGOING GRANT OF RIGHTS IN SECTION 2.3 INCLUDES PUBLIC PERFORMANCE RIGHTS. PUBLIC PERFORMANCE RIGHTS INCLUDE THE RIGHTS TO PLAY YOUR SONGS IN PUBLIC VENUES SUCH AS RESTAURANTS, CAFES, PARKS AND STORES. IF YOU HAVE ALREADY GRANTED YOUR PUBLIC PERFORMANCE RIGHTS TO A PERFORMANCE RIGHTS ORGANIZATION (&quot;PRO&quot;) SUCH AS BMI, ASCAP OR SESAC, THEN:</strong></p>

    <p>a) YOU MAY BE PROHIBITED FROM GRANTING THE SAME RIGHTS TO US, OR</p>

    <p>b) A GRANT OF PUBLIC PERFORMANCE RIGHTS TO US MAY PREVENT A PRO FROM COLLECTING ROYALTIES ON YOUR BEHALF. IN CERTAIN SITUATIONS A PRO MAY REQUIRE THAT AN ARTIST PROVIDE THE PRO WITH NOTICE IF THE ARTIST IS GRANTING PUBLIC PERFORMANCE RIGHTS TO ANOTHER PARTY. IF YOU HAVE AN AGREEMENT WITH A PRO, WHICH INCLUDES SUCH A PROVISION, YOU ARE SOLELY RESPONSIBLE FOR PROVIDING SUCH NOTICE TO THE PRO.</p>

    <p><strong>2.4 PROMOTIONAL LICENSE GRANTS.</strong> Except as expressly provided in EarDish’s Privacy Policy, you hereby grant EarDish an unrestricted, assignable, sub-licensable, revocable, royalty-free license throughout the universe to reproduce, distribute, publicly display, communicate to the public, publicly perform (including by means of digital audio transmissions) on a through-to-the-audience basis, create derivative works from, transmit to Third Party Sites and Hosting Services, and otherwise use and exploit (collectively, &quot;<strong>Use</strong>&quot;) all User Content you upload to or through the Service or to us through email (excluding only Reserved User Content as defined below), through any media and formats now known or hereafter developed, including Third Party Sites, Hosting Services, and Applications, for the purposes of:</p>

    <p>a)  Advertising, marketing, and promoting (including through the public performance, public display, making available, and communicating to the public) you, your User Content, EarDish, and the Service, in EarDish’s sole discretion;</p>

    <p>b)  Distributing your User Content and information about you and your User Content to the public, either directly or through Third Party Sites, in accordance with your user settings in the EarDish Editor;</p>

    <p>c)  Sharing information about your User Content with third parties, Hosting Services and Third Party Sites for any use or purpose selected by EarDish, including, by way of example and not limitation, for use in charting the popularity of User Content on the Service and making your calendar of appearances publicly available;</p>

    <p>d)  Providing biographical information about you and your User Content in connection with your involvement with any event, good or service;</p>

    <p>e)  Transmitting or distributing your User Content to Third Party Sites and/or Hosting Services or other data or cloud computing service providers, for the purpose of reproducing, hosting, storing, and managing or storing your User Content; and</p>

    <p>f)  Transmitting or distributing your User Content to any other third party authorized by you to access such User Content. You further grant EarDish a royalty free license to Use your name, image, voice, likeness, and any photographs or artwork (e.g., album cover artwork) made available by or on your behalf through the Service in conjunction with advertising, marketing, or promoting you, your User Content, EarDish or the Service.</p>

    <p><strong>FOR THE AVOIDANCE OF DOUBT, THE RIGHTS GRANTED IN THE PRECEDING SENTENCES OF THIS SECTION 2.4 INCLUDE, BUT ARE NOT LIMITED TO, THE RIGHT TO REPRODUCE SOUND RECORDINGS (AND MAKE MECHANICAL REPRODUCTIONS OF THE MUSICAL WORKS EMBODIED IN SUCH SOUND RECORDINGS), PUBLICLY PERFORM SOUND RECORDINGS AND MUSIC VIDEOS (AND THE MUSICAL WORKS EMBODIED THEREIN), AND PUBLICLY DISPLAY ANY LYRICS UPLOADED BY YOU TO THE SERVICE, ALL ON A ROYALTY FREE BASIS.</strong></p> 
    <p>This means that you are granting EarDish the right to Use the User Content you upload to and through the Service without the obligation to pay any royalties to any sound recording copyright owner (e.g., a record label), a musical work copyright owner (e.g., a music publisher), a musical works performing rights organization (a &quot;<strong>PRO</strong>&quot;) (e.g., ASCAP, BMI and SESAC in the United States or comparable PROs outside of the United States such as PRS for Music in the United Kingdom), a sound recording PRO (e.g., SoundExchange, Inc.), any unions or guilds (e.g., the American Federation of Television and Radio Artists (&quot;<strong>AFTRA</strong>&quot;) or American Federation of Musicians (&quot;<strong>AFM</strong>&quot;)), and engineers, producers or other participants involved in the creation of User Content.</p>

    <p><strong>2.5 LIMITATIONS ON GRANT OF RIGHTS TO EARDISH.</strong>  Notwithstanding the grant of rights in Sections 2.3 and 2.4, nothing contained in these Terms grants EarDish a right or license to:</p>

    <p>a)  Sell phonorecords (e.g., CDs, LPs or digital downloads) of User Content;</p>

    <p>b)  Authorize third parties to incorporate any User Content in any audio-only or audiovisual commercials, television programs, movies or any similar audiovisual works; or</p>

    <p>c)  Use User Content to promote any other good or service other than you, your User Content, EarDish or the Service, <strong>UNLESS</strong> your User Content is Used to <strong>advertise, market, or promote YOU or YOUR creative works,</strong> including, but not limited to, your association with or <strong>appearance at an event where YOU are scheduled to perform</strong> or <strong>appear or have performed or appeared as an artist, or are scheduled to be honored or have been honored as an artist.</strong></p>

    <p><strong>2.6 WAIVER OF RIGHTS.</strong>  By uploading User Content to or through the Service you waive any rights to prior inspection or approval of any marketing or promotional materials related to such User Content. You further waive any and all rights of privacy, publicity, or any other rights of a similar nature in connection with your User Content, or any portion thereof, including, without limitation, your name, likeness, voice, image, and persona or any advertising or publicity relating thereto. To the extent any moral rights are not transferable or assignable, you hereby waive and agree never to assert any and all moral rights, or to support, maintain or permit any action based on any moral rights that you may have in or with respect to any User Content you upload to or through the Service, during the term of these Terms. You expressly release EarDish and all of EarDish’s agents, partners, subsidiaries, affiliates, licensees, successors, and assigns from any and all claims, demands, liabilities, or causes of action, whether now known or unknown, for defamation, copyright infringement, violation of moral rights, and invasion of the rights to privacy, publicity, or personality or any similar matter, or based upon or relating to the Use of your User Content. Notwithstanding the preceding sentences of this Section 6.6, you should let us know immediately if you object to any uses of your User Content on or through the Service or in the promotion of the Service. We will consider all reasonable requests to terminate any Use that you find objectionable, but we shall have no liability to you for any Use authorized in these Terms.</p>

    <p><strong>2.7 OWNER REQUIREMENTS AND/OR FULL AUTHORIZATION TO GRANT RIGHTS TO USER CONTENT.</strong>  If you are not the copyright owner of or are not fully authorized to grant rights in all of the elements of the User Content you intend to upload or transmit to or through the Service, including to any Hosting Services or Third Party Sites, then you must not upload the User Content to or through the Service. In addition, if you only own the rights in and to a sound recording, for example, but not to the underlying musical works embodied in such sound recordings, then you must not upload such sound recordings to the Service unless you obtain all necessary rights, authorizations, and permissions with respect to such embedded musical works that grant you sufficient rights to sublicense to EarDish according to these Terms. For example, cover songs are not permitted on the Service unless you have cleared all rights to the song covered by the artist/band and/or rights holder(s).</p>

    <p><strong>2.8 PRO COMPLIANCE FOR MUSICAL WORKS.</strong>  If you are a composer or author of a musical work and have affiliated with a PRO, then you must notify your PRO of the royalty free license granted by you to EarDish through these Terms. Each PRO has different rules with respect to providing notification for a direct license. You are solely responsible for ensuring your compliance with the relevant PRO’s reporting obligations. If you have assigned your rights to a music publisher, then you must obtain the consent of such music publisher to grant the royalty free license set forth in these Terms or have such music publisher enter into these Terms with EarDish. Just because you authored a musical work (e.g., wrote a song) doesn’t mean you have the right to grant EarDish the licenses contained in these Terms.</p>

    <p><strong>2.9 CONFIRMATION OF RIGHTS.</strong>  EarDish reserves the right to demand confirmation from you in writing of all authorizations, licenses, permissions, and consents obtained by you (if any) with respect to any third-party materials embodied in User Content you upload to or transmit through the Service. If you fail to provide us with such confirmation upon request, we reserve the right to remove or deny access to any or all of your User Content available on or through the Service and to suspend or terminate your account with EarDish. We will have no liability to you for any actions taken by us pursuant to this Section 2.9.</p>

    <p><strong>2.10 RIGHTS FOR THIRD PARTY SITES: THROUGH TO THE AUDIENCE RIGHTS.</strong> For clarification purposes, the rights granted by you in these Terms include the right of EarDish to Use User Content you upload or submit to or through the Service through the Site and Third Party Sites, such as Facebook, and all of the rights granted herein by you are provided on a through-to-the-audience basis, meaning the owners or operators of such Third Party Sites will not have any separate liability to you or any other third party (e.g., a PRO) for User Content uploaded to, transmitted, reproduced or publicly performed or displayed through the Service or such Third Party Sites, or otherwise made available to or through such Third Party Sites.</p>

    <p><strong>2.11 PORTABILITY OF USER CONTENT.</strong> Once you upload or transmit User Content on or through the Service, you may be entitled to make your User Content available through Third Party Sites. We may from time to time offer Applications (including widgets and application programming interfaces) that you may place on Third Party Sites or that allow you to transmit or distribute your User Content to Third Party Sites. We may or may not permit you to limit the amount of your User Content available through such Applications.</p>

    <p><strong>2.12 REPRESENTATIONS AND WARRANTIES WITH REGARD TO USER CONTENT.</strong> By uploading or transmitting User Content to or through the Service, you hereby represent and warrant to EarDish that (a) you have obtained all necessary rights, permissions, authorizations, licenses, and clearances to grant the licenses and rights set forth in these Terms with respect to such User Content and (b) the Use of such User Content in a manner consistent with these Terms will not (i) infringe the rights of any third party, including copyright, trademark, patent and other intellectual property rights or other protected rights, such as the rights of privacy or publicity, or (ii) require EarDish or any Third Party Site on or through which the Service is made available to pay any fees of any kind to any third party, including, but not limited to, any sound recording copyright owner, any musical work copyright owner, any PRO (musical work or sound recording), any union, guild, non-featured vocalist or musician, engineer, producer, co-author, record royalty participant or any other person or entity, or any use or re-use fees for the Use of any sound recording or audiovisual work. <strong>WARNING: YOU MAY NOT UPLOAD TO OR THROUGH THE SERVICE, WHETHER IN WHOLE OR IN PART, ANY USER CONTENT FOR WHICH YOU DO NOT OWN, CONTROL OR HAVE EXPRESS WRITTEN AUTHORIZATION TO USE. IF YOU UPLOAD CONTENT OWNED BY A THIRD PARTY WITHOUT AUTHORIZATION OR AS OTHERWISE PERMITTED BY LAW, THEN YOU MAY BE SUBJECT TO LIABILITY TO THE THIRD PARTY OWNERS OF SUCH CONTENT AS WELL AS TO EARDISH. EARDISH MAY ASSIST THIRD PARTIES IN ENFORCING THEIR RIGHTS, WITHOUT ANY LIABILITY TO YOU. EARDISH MAY TERMINATE YOUR RIGHT TO USE THE SERVICE FOR A VIOLATION OF THIS SECTION.</strong></p>

    <p><strong>2.13 PROHIBITED CONTENT AND COMMERCE.</strong>  EarDish prohibits the use of the Services by any person or entity that engages in any of the following:</p>

    <p>a)  Provides, sells or offers to sell the following products or content (or services related to the same): pornography or illicitly pornographic sexual products; escort services; illegal goods; illegal drugs; illegal drug contraband; pirated computer programs; instructions on how to assemble or otherwise make bombs, grenades or other weapons.</p>
     
    <p>b) Displays material that exploits children, or otherwise exploits children under 18 years of age.</p>

    <p>c) Provides, sells or offers products, services or content frequently associated with unsolicited commercial email, or spam, such as online pharmacies, work at home businesses, credit or finance management, mortgage and debt relief offers.</p> 

    <p>d) Provides material that is grossly offensive, including blatant expressions of bigotry, prejudice, racism, hatred or excessive profanity or post any obscene, lewd, lascivious, filthy, excessively violent, harassing or otherwise objectionable content. </p>

    <p>e) Posts or discloses any personally identifying information or private information about children without their consent (or their parents consent in case of a minor). </p>

    <p>f) Sells or promotes any products or services that are unlawful in the location at which the content is posted or received. </p>

    <p>g) Introduces viruses, worms, harmful code and/or Trojan horses on the Internet. </p>

    <p>h) Promotes, solicits or participates in pyramid schemes or multi-level marketing (MLM) businesses. </p>

    <p>i) Engages in any libelous, defamatory, scandalous, threatening, harassing activity. </p>

    <p>j) Posts any content that advocates, promotes or otherwise encourages violence against any governments, organizations, groups or individuals or which provides instruction, information or assistance in causing or carrying out such violence. </p>

    <p>k) Provides content, including images, of authors, artists, photographers or others without the express written consent of the content owner. </p>

    <p><strong>2.14 RESERVE RIGHTS TO PROHIBIT USAGE.</strong>  EarDish reserves the right to prohibit the use of the Services by any person or entity if EarDish, believes in its sole discretion, that such use may violate any federal, state or local, law, rule or regulation.</p>

    <p><strong>2.15 OTHER INVENTIONS AND CONCEPTS.</strong> You further grant to EarDish a royalty free license throughout the universe to use, without any payment or accounting to you or any other third party, any concepts, know-how, ideas or inventions that you (and those who act on your behalf) upload or transmit to or through the Service or to us through email.</p>

    <p><strong>3.0 USE OF SERVICES.</strong> You understand that the Services and the Web Site are available for your personal use only. Your use of any Services that provide for or facilitate commercial transactions may be subject to additional terms and conditions. Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that we shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between you and any third party, you understand and agree that we are under no obligation to become involved. In the event that you have a dispute with a third party including other members of the Web Site, you hereby release the Company, its officers, employees, agents and successors in rights from claims, demands and damages (actual and consequential) of every kind or nature, known or unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to such dispute and/or our Services.</p>

    <p>If you are a California resident, <strong>you waive California Civil Code Section 1542</strong>, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.</p>

    <p>You agree not to harvest or collect email addresses or other contact information of other Web Site users by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications. Additionally, you agree not to use automated scripts to collect information from the Web Site. You agree that you will not use the Web Site in any unlawful manner or in any other manner that could damage, disable, overburden or impair the Web Site. </p>

    <p>In addition, you agree not to use the Service to: </p>

    <p>a)  Create a false identify or impersonate another person or entity in any way;</p>

    <p>b)  Upload or otherwise transmit to or through the Service any information or content that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party, including by incorporating any such material in User Materials;</p>

    <p>c)  Upload or otherwise transmit to or through the Service any unlawful, harmful, harassing, defamatory, threatening, vulgar, sexually explicit, hateful or otherwise objectionable material of any kind, any material that can cause harm or delay to the Service or computers of any kind;</p>

    <p>d)  Upload, post or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes or any other form of solicitation (commercial or otherwise);</p>

    <p>e)  Restrict, discourage or inhibit any person from using the Service, disclose personal information about a third person on the Service or obtained from the Service without the consent of such person or collect information about users of the Service;</p>

    <p>f)   Undertake, cause, permit or authorize the modification, creation of derivative works, translation, reverse engineering, decompiling, disassembling or hacking of any aspect of the Service or any part thereof, or attempt to do any of the foregoing, except and solely to the extent permitted by these Terms, the authorized features of the Service, or by law, or otherwise attempt to use or access any portion of the Service other than as intended by EarDish; </p>

    <p>g)  Gain unauthorized access to the Service, to other users’ accounts, names or personally identifiable information, or to other computers or websites connected or linked to the Service;</p>

    <p>h)  Reproduce, distribute, publicly display, publicly perform, sell, trade, resell or exploit any portion of the Service, use of the Service, access to the Service or content obtained through the Service, for any purpose other than expressly permitted by these Terms, including, by way of example and not limitation, by doing or engaging in any of the following without EarDish’s express written consent:</p>

    <p>i)  Copying, caching or reformatting any User Materials for commercial purposes in any fashion whatsoever, whether by copying to physical or electronic media for purposes of buffering delivery or converting transmissions from the Service to alternative delivery formats;</p>

    <p>j)  Framing, embedding and/or passing off User Materials obtained from the Service in such a manner as to present them as originating from a source other than the Service;</p>

    <p>k)  Altering, defacing, mutilating or otherwise bypassing any approved software through which the Service is made available;</p>

    <p>l)  Using any trademarks, service marks, design marks, logos, photographs or other content belonging to EarDish or obtained from the Service, without expressed written consent from the company.</p>

    <p>m)  Post, transmit or otherwise make available any virus, worm, spyware or any other computer code, file or program that may or is intended to damage or hijack the operation of any hardware, software or telecommunications equipment, or any other aspect of the Service or communications equipment and computers connected to the Service;</p>

    <p>n)  Remove, disable, damage, circumvent or otherwise interfere with any security-related features of the Service, features that prevent or restrict the use or copying of any part of the Service or any content on the Service, or features that enforce limitations on the use of the Service or any content on the Service;</p>

    <p>o)  Use any scraper, spider, robot or other automated means of any kind to access the Service, except and solely to the extent permitted by these Terms and the features of the Service, deep-link to any feature or content on the Service, bypass our robot exclusion headers or other measures we may use to prevent or restrict access to the Service;</p>

    <p>p)  Interfere with or disrupt the Service, networks or servers connected to the Service or violate the regulations, policies or procedures of such networks or servers;</p>

    <p>q)  Violate any applicable federal, state or local laws or regulations or these Terms; or Assist or permit any persons in engaging in any of the activities described above.</p>

    <p>r)  Upload, post, email, transmit or otherwise make available any Content that we deem to be harmful, threatening, abusive, harassing, vulgar, obscene, hateful, or racially, ethnically or otherwise objectionable; </p>

    <p>s)  Upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation;</p>

    <p>t)  Upload, post, email, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; or </p>

    <p>u)  Use or attempt to use another user's account, without authorization from the Company, or create a false identity using the Services or the Web Site.</p>

    <p><strong>You may not download or copy music files from the Service</strong>, additionally, you agree to comply with the following Usage Rules: </p>

    <p>a)  Your use of the music files is conditioned upon your prior acceptance of these Terms and Conditions of Use;</p>

    <p>b)  You shall be authorized to listen to the music files only for personal, noncommercial use; </p>

    <p>c)  You may not combine a music file with any video or image file to create a multimedia work;</p>

    <p>d)  You may not use a music file as a musical "ringer" in connection with a phone or phone calls; </p>

    <p>e)  The playback of a music file does not transfer to you any commercial or promotional use rights in the music file; and </p>

    <p>f)  You agree that your playback of music files constitutes your acceptance of and agreement to the Terms and Conditions of Use and these Usage Rules, and that any use of the music files other than in accordance with these Usage Rules may constitute a copyright infringement.</p>

    <blockquote><strong>The Company reserves the right to modify the Usage Rules at any time.</strong></blockquote>

    <p><strong>3.1 ACCURACY OF INFORMATION.</strong> You agree to provide true, accurate, current, and complete information about yourself as requested in any registration forms required by EarDish. You also agree to update the information about yourself promptly, and as necessary, to keep it current and accurate. If messages sent to an email address provided by you are returned as undeliverable, EarDish reserves the right to terminate your account immediately with or without notice to you and without any liability to you or any third party. </p>

    <p><strong>3.2 POSTING VIOLATIONS.</strong> EarDish may provide Forums on which users of the Service may communicate with one another. Any violation by you of the following terms and conditions regarding your use of the Forums may result in the termination of your right to post messages to one or all Forums or to your use of the Service, in EarDish’s sole discretion and without any liability to you.</p>

    <p><strong>3.3 SCREEN NAMES REFUSAL.</strong> EarDish may refuse to grant you, and you may not use, a screen name (or email address) that is already being used by someone else, impersonates another person, belongs to another person, violates the intellectual property or other rights of any person, or is vulgar or otherwise offensive in EarDish’s sole discretion.</p>

    <p><strong>3.4 USER RESPONSIBILITY FOR CONTENT.</strong> You are responsible for any User Content you include in a post, and assume all liability arising out of a post. You agree, represent, and warrant that any information and User Content you post is: truthful, accurate, not misleading and offered in good faith; not invasive of another’s privacy, abusive, threatening or obscene; and not infringing upon the copyright, trademark, patent or other intellectual property rights of others. You further agree, represent, and warrant that you have the right to post or transmit such information or User Content and to grant the rights set forth in these Terms. The content of such information, whether publicly posted or privately transmitted, is your sole responsibility.</p>

    <p><strong>3.5 NO CONFIDENTIALITY.</strong> You must not post any material that you consider to be confidential or proprietary. Any messages or User Content that you post will be considered non-confidential and non-proprietary, and treated as such by EarDish, and may be used by EarDish and others for any purpose with or without notice to you.</p>

    <p><strong>3.6 REMOVAL OF POSTINGS.</strong> You may remove any of your messages posted at your discretion or by sending an email to <a href="mailto:help@EarDish.com">help@EarDish.com</a>, and requesting that the particular message be removed; provided, however, that the removal of a message will not ensure the deletion of your message from computer servers owned or operated by or on behalf of EarDish or the removal of your message from the files of any third parties who may have copied or further distributed your messages. As such, your message may continue to be made publicly accessible indefinitely by such third parties.</p>

    <p><strong>3.7 LICENSE GRANTS FOR POSTINGS.</strong> You own and retain any copyright you may have in any message you post. Nevertheless, by posting a message, you automatically grant EarDish a royalty free, perpetual, irrevocable, assignable, non-exclusive license throughout the universe to Use your message (or any portion thereof, including an edited version) alone or as part of other works in any form, media, or technology whether now known or hereafter developed, and to sublicense such rights through multiple tiers of sub-licensees, with or without attribution to you. You further grant end users of the Service a royalty free license to Use your messages solely for personal, non-commercial Uses without the need for attribution. You further grant EarDish a royalty free, perpetual, irrevocable, assignable, non-exclusive license throughout the universe to any concepts, know-how, ideas or inventions that you post.</p>

    <p><strong>3.8 MONITORING AND REMOVAL RIGHTS FOR USER SUBMISSIONS.</strong> EarDish does not control User Content or postings (together, &quot;<strong>User Materials</strong>&quot;) and does not have any obligation to monitor such User Materials for any purpose. Further, EarDish has no obligation to permit User Materials to be made available on or through the Service. EarDish may choose, in its sole discretion, to monitor, review, or otherwise access some or all User Materials, but by doing so EarDish nonetheless assumes no responsibility for the User Materials, no obligation to modify or remove any inappropriate User Materials, or to monitor, review, or otherwise access other User Materials, and EarDish assumes no responsibility for the conduct of the third party or user submitting or transmitting any User Materials to or through the Service. You acknowledge that EarDish may or may not pre-screen User Materials, and that EarDish and its designees shall have the right (but not the obligation), in their sole discretion, to pre-screen, refuse, or remove any User Materials that are available on or through the Service. Without limiting the foregoing, EarDish and its designees may, at any time and without prior notice, remove any User Materials that, in the sole judgment of EarDish, violate these Terms, are otherwise objectionable, or for any other reason, with or without notice and with no liability of any kind. You agree that you will evaluate, and bear all risks associated with the use of any User Materials or other content available on or through the Service, including any reliance on the accuracy, completeness, usefulness or legality of such User Materials or other content. You should exercise good judgment before downloading any User Materials as EarDish makes no representations or warranties with respect to any User Materials made available on or through the Service.</p>

    <p><strong>3.9 REPORTING OF USER MATERIALS.</strong> If you locate any User Materials on or through the Service that you find offensive or objectionable, you may report such User Materials to EarDish by sending an email to <a href="mailto:report@EarDish.com">report@EarDish.com</a>. EarDish reserves the sole right, but not the obligation, to remove any message that it deems inappropriate in its sole and absolute discretion and without any liability to you. If you believe any User Materials are infringing of your intellectual property rights, please report such User Materials pursuant to Section 17.0 of these Terms.

    <p><strong>3.10 NO ENDORSEMENT.</strong> EarDish does not endorse, support, represent or guarantee the truthfulness, accuracy, or reliability of any messages posted within our service. The opinions expressed in any posting are to be attributed solely to the person or entity that posted such message. Any reliance you place on material or information set forth in a posted message will be at your own risk.</p>

    <p><strong>4.0 DISCLAIMER OF USER MATERIALS.</strong>  <em>YOU UNDERSTAND THAT WHEN USING THE SERVICE, YOU MAY BE EXPOSED TO MESSAGES AND USER CONTENT FROM A VARIETY OF SOURCES, AND THAT EARDISH IS NOT RESPONSIBLE FOR THE ACCURACY, INTEGRITY, QUALITY, LEGALITY, USEFULNESS, SAFETY OR INTELLECTUAL PROPERTY RIGHTS OF OR RELATING TO SUCH USER MATERIALS. YOU FURTHER UNDERSTAND AND ACKNOWLEDGE THAT YOU MAY BE EXPOSED TO USER MATERIALS THAT ARE INACCURATE, OFFENSIVE, INDECENT, OR OBJECTIONABLE, AND YOU AGREE TO WAIVE, AND HEREBY DO WAIVE, ANY LEGAL OR EQUITABLE RIGHTS OR REMEDIES YOU HAVE OR MAY HAVE AGAINST EARDISH WITH RESPECT THERETO. UNDER NO CIRCUMSTANCES WILL EARDISH BE LIABLE IN ANY WAY FOR OR IN CONNECTION WITH ANY USER MATERIALS, INCLUDING, BUT NOT LIMITED TO, FOR ANY INACCURACIES, ERRORS OR OMISSIONS IN ANY USER MATERIALS, OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY USER MATERIALS POSTED, EMAILED, UPLOADED OR OTHERWISE DISPLAYED, PERFORMED OR TRANSMITTED VIA THE SERVICE. BY ACCESSING OR USING ANY USER MATERIALS TRANSMITTED ON OR THROUGH THE SERVICE, YOU WAIVE ANY AND ALL CLAIMS AGAINST EARDISH THAT YOU MAY HAVE ARISING OUT OF OR RELATING TO SUCH USER MATERIALS.</em></p>

    <p><strong>5.0 THIRD PARTY USE OF SERVICE.</strong>  EarDish may provide the Service through the Website, Third Party Sites, other channels owned or operated by or on behalf of EarDish, Applications, and any other media or channels now known or hereafter developed. The Service may require that you agree to additional terms and conditions, including those of Third Party Sites. Any terms and conditions required by EarDish for use of any portion of the Service offered by EarDish (but not those of any Third Party Site) will, unless otherwise expressly stated in such terms, supersede these Terms in the event of a conflict only as to the services with respect to which those terms relate. Such additional terms and conditions (if any) (but not those of any Third Party Site) are hereby incorporated into and made a part of these Terms by reference. You may also be subject to the terms of use of any Third Party Sites and you are solely responsible for your acceptance of and compliance with such terms.</p>

    <p><strong>6.0 AGE LIMITATIONS.</strong>  The Service is not intended for children under the age of 13. <strong>IF YOU ARE UNDER 13 YEARS OF AGE, YOU MUST NOT USE OR ACCESS THE SERVICE AT ANY TIME OR IN ANY MANNER.</strong> EarDish does not seek through the Service to gather personal information from or about children under the age of 13. Individuals under the age of 13 are prohibited from accessing the Web Site without verified parental consent furnished to the Company in accordance with the Children's Online Privacy Protection Act of 1998. You hereby represent and warrant that you are 13 years of age or older. <strong>SOME AREAS OF THE WEB SITE MAY CONTAIN MATERIAL THAT IS INAPPROPRIATE FOR MINORS.</strong></p>

    <p><strong>7.0 SERVICE VIOLATIONS.</strong>  You must exercise caution, good sense and sound judgment when using the Service. You are prohibited from violating, or attempting to violate, the security of the Service. Any such violations may result in criminal and/or civil penalties against you, as well as the termination of your privilege to use the Service, at EarDish’s sole discretion. EarDish reserves the right to investigate any alleged or suspected violations and, if a criminal violation is suspected, refer such suspected violation to the appropriate law enforcement agencies and cooperate fully with such investigations, including, but not limited to, the disclosure of any or all of your activities on or related to the Service. </p>

    <p><strong>8.0 PUBLISHING OF CONTENT.</strong> You hereby acknowledge and agree that you are solely responsible for all materials that you post or publish on the Web Site, including without limitation, information, code, data, text, software, music, sound, links, photographs, pictures, graphics, video, chat, messages, files and any other materials ("Content"). You represent, warrant and agree that no Content submitted by you or through your account will violate or infringe upon the rights of any third party, including copyright, trademark, privacy, publicity or other personal or proprietary rights; or contain libelous, defamatory or otherwise unlawful material. You represent and warrant that you have all legal rights necessary to publish any Content on the Web Site or that you own such Content. You hereby acknowledge and agree that Company shall, at all times, possess the right to refuse to include and/or to cause the removal of any or all of your Content for any reason and at its sole discretion. You hereby acknowledge and agree that Company may, at its sole discretion, disclose your Content in order to: </p>

    <p>a)  Comply with law enforcement, court orders, or the legal process; and/or</p>
     
    <p>b) Protect the rights and safety of individuals; and/or </p>

    <p>c) Settle disputes over intellectual property ownership.</p>

    <p><strong>9.0 INTELLECTUAL PROPERTY RIGHTS.</strong>  The content made available on or through the Service, including without limitation, any text, software, graphics, photos, sounds, music, videos, games and interactive features, may be protected by copyright or other intellectual property rights and owned by EarDish or third party licensors of EarDish. No material from the Service may be copied, reproduced, republished, uploaded, posted, transmitted, or distributed in any way without written permission of the copyright owner.  Modification of materials obtained from the Service, including, but not limited to, User Materials, for any other purpose, including, without limitation, any commercial purpose, is a violation of the copyrights and other proprietary rights of EarDish or its licensors, unless you have obtained express written authorization to the contrary. Permission for all other uses of materials on or obtained through the Service, including reproducing and distributing multiple copies, or linking to any page of the Service (excluding our &quot;home page&quot; at www.EarDish.com) must be obtained from EarDish in advance and in writing. Requests for such authorization should be submitted via an email to <a href="mailto:help@EarDish.com">help@EarDish.com</a>. For purposes of these Terms, the use of any such material on any other website or networked computer environment is prohibited. All design rights, databases and compilation and other intellectual property rights, in each case whether registered or unregistered, and related goodwill, are proprietary to EarDish.</p>

    <p><strong>9.1 TRADEMARKS.</strong> All trademarks, service marks, logos and trade names on the Service, whether registered or unregistered, are proprietary to EarDish or to other companies where so indicated. You may not reproduce, download or otherwise use any such trademarks, service marks, logos or trade names without the prior written consent of the appropriate owner thereof.</p>

    <p><strong>9.2 NO IMPLIED RIGHTS.</strong> There are no implied licenses granted in these Terms of Service.</p>

    <p><strong>10.0 LINKS TO THIRD PARTY SITES AND HOSTING SERVICES.</strong>  As you use the Service you may notice links to Third Party Sites and Hosting Services. These links are for convenience only. If you use these links, you will leave the Service. Certain of these Third Party Sites and Hosting Services may make use of EarDish proprietary intellectual property rights (such as copyrights, trademarks, service marks, logos and trade names) under license from EarDish. EarDish is not responsible for the availability or content of these Third Party Sites or Hosting Services, or for any viruses or any other damaging elements, (including but not limited to financial damages, technical delays, etc.) encountered in linking to a Third Party Site or Hosting Service, whether or not EarDish is affiliated with the owners of such Third Party Sites or Hosting Services. In addition, the provisioning of links to Third Party Sites and Hosting Services is not an endorsement or approval by EarDish of the organizations owning, operating or sponsoring such Third Party Sites or Hosting Services, or their products or services. These Terms do not apply to Third Party Sites and Hosting Services, and you should review applicable terms and policies, including any relevant privacy policies, associated with any Third Party Sites, Hosting Services, applications, software or services. Notwithstanding the immediately preceding sentence, the use of any portion or feature of the Service available on or through a Third Party Site or Hosting Service will continue to be subject to these Terms.</p>

    <p><strong>10.1 THIRD PARTY LIABILITY RELEASE.</strong> YOU AGREE THAT EARDISH WILL NOT BE RESPONSIBLE OR LIABLE FOR ANY LOSS OR DAMAGE OF ANY SORT INCURRED AS THE RESULT OF ANY SUCH DEALINGS YOU MAY HAVE ON OR THROUGH A THIRD PARTY SITE OR HOSTING SERVICE, OR AS THE RESULT OF THE PRESENCE OF ANY THIRD PARTY ADVERTISING ON THE SERVICE.</p>

    <p><strong>11.0 INDEMNITY.</strong>  You agree to indemnify, defend, and hold harmless EarDish and its parent, subsidiaries, affiliates, investors, partners, sub-licensees or any related companies, licensors and suppliers, and their respective directors, officers, employees, agents, representatives, contractors, and assigns and other EarDish users who use any User Materials you upload to or make available on or through the Service, from all damages, injuries, liabilities, costs, fees and expenses, (including, but not limited to, attorneys’ fees and court costs) arising from or in any way related to: </p>

    <p>a)  Your use or misuse of the Service;</p>
     
    <p>b) Your User Material, including EarDish’s or any user’s Use of your User Material consistent with these Terms; </p>

    <p>c) Your breach or other violation of these Terms including any representations, warranties and covenants herein; or </p>

    <p>d) Your violation of the rights of any other person or entity, including, but not limited to, claims that any User Material infringes or violates any third-party intellectual property rights or other proprietary rights, including any claims for the payment of so-called mechanical royalties, synchronization royalties, master use royalties, public performance royalties, or any other royalties claimed by any owner or other party claiming any right in or to all or any portion of any User Material uploaded or transmitted by you on or through the Service. Notwithstanding the foregoing, EarDish reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify EarDish if EarDish, in its reasonable discretion, concludes that you are not adequately protecting EarDish’s interests or are incapable of protecting EarDish’s interests, and you agree to cooperate with EarDish’s defense of these claims. You agree not to settle any matter without the prior written consent from EarDish. EarDish will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>

    <p><strong>12.0 SPECIAL PROVISIONS APPLICABLE TO USERS OUTSIDE OF THE UNITED STATES.</strong>  The following provisions apply to users and non-users who interact with EarDish outside the United States:</p>

    <p>a)  You consent to having your personal data transferred to and processed in the United States.</p>

    <p>b)  If you are located in a country embargoed by the United States, or are on the U.S. Treasury Department's list of Specially Designated Nationals you will not engage in commercial activities on EarDish (such as advertising or payments) or operate a Platform application or website.</p>

    <p>c)  Access to the Service from jurisdictions where the contents or practices of the Service are illegal, unauthorized or penalized is strictly prohibited.</p>

    <p><strong>13.0 DISCLAIMERS.</strong>  THE SERVICE, USER MATERIALS, AND ANY THIRD-PARTY CONTENT, SOFTWARE, SERVICES OR APPLICATIONS MADE AVAILABLE ON OR THROUGH OR IN RELATION TO THE SERVICE, ARE PROVIDED ON AN <strong>&quot;AS IS,&quot; &quot;AS AVAILABLE,&quot; &quot;WITH ALL FAULTS&quot;</strong> BASIS WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY OR OTHERWISE.  TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, EARDISH AND ITS AFFILIATES, PARTNERS, LICENSORS, AND SUPPLIERS HEREBY DISCLAIM ALL EXPRESS, IMPLIED AND STATUTORY WARRANTIES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM EARDISH, AN EMPLOYEE OR REPRESENTATIVE OF EARDISH OR THROUGH THE SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. EARDISH AND ITS AFFILIATES, PARTNERS, LICENSORS, AND SUPPLIERS DO NOT WARRANT THAT THE SERVICE OR ANY PART THEREOF, OR ANY PRODUCTS OR CONTENT OFFERED THROUGH THE SERVICE, WILL BE UNINTERRUPTED, OR FREE OF ERRORS, VIRUSES OR OTHER HARMFUL COMPONENTS AND DO NOT WARRANT THAT ANY OF THE FOREGOING WILL BE CORRECTED. YOU UNDERSTAND AND AGREE THAT YOU USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAIN INFORMATION, MATERIALS, OR DATA THROUGH THE SERVICE OR ANY ASSOCIATED SITES OR APPLICATIONS AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM USED IN CONNECTION WITH THE SERVICE) OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OR USE OF SUCH MATERIAL OR DATA.</p>

    <p><strong>14.0 LIMITATION OF LIABILITY.</strong>  IN NO EVENT WILL EARDISH OR ITS OFFICERS, DIRECTORS, LICENSORS OR SUPPLIERS BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, SPECIAL OR OTHER CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE OR ACCESS OF OR INABILITY TO USE OR ACCESS THE SERVICE OR ANY CONTENT (INCLUDING USER CONTENT) MADE AVAILABLE THROUGH THE SERVICE, INCLUDING, WITHOUT LIMITATION, ANY LOST PROFITS, BUSINESS INTERRUPTION, OR OTHERWISE, WHETHER BASED IN TORT, CONTRACT OR OTHER LEGAL THEORY, EVEN IF EARDISH OR ITS LICENSORS OR SUPPLIERS ARE EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL EARDISH OR ITS LICENSORS OR SUPPLIERS BE LIABLE IN THE AGGREGATE FOR ANY DAMAGES INCURRED BY YOU THAT EXCEED THE GREATER OF ONE HUNDRED DOLLARS ($100) OR THE AMOUNT YOU HAVE PAID US IN THE PAST TWELVE MONTHS. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, EARDISH’S LIABILITY WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.</p>

    <p><strong>15.0 LIMITATIONS; BASIS OF THE BARGAIN.</strong>  APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, YOU AGREE THAT BECAUSE SUCH WARRANTY DISCLAIMERS AND LIMITATIONS OF LIABILITY REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND EARDISH, AND ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN YOU AND EARDISH, EARDISH’S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW. YOU UNDERSTAND AND AGREE THAT EARDISH WOULD NOT BE ABLE TO OFFER THE SERVICE TO YOU ON AN ECONOMICALLY FEASIBLE BASIS WITHOUT THESE LIMITATIONS.</p>

    <p><strong>16.0 TERM AND TERMINATION.</strong> These Terms, as amended, will be effective commencing with your first use or registration of the Service and will remain in full force and effect throughout your use of the Service.</p>

    <p><strong>16.1 TERMINATION BY EARDISH.</strong>  EarDish may terminate your use of the Service or any of our features or services at any time and for any reason, with or without notice, for conduct violating these Terms or upon EarDish’s sole determination. You hereby agree to EarDish’s broad right of termination. Upon any such termination, you must destroy all materials obtained from the Service and all copies thereof, including any copies downloaded by you for your personal, noncommercial use. You agree that if your use of the Service is terminated pursuant to these Terms, you will not attempt to use the Service under any name, real or assumed, and further agree that if you violate this restriction after being terminated, you will indemnify and hold us harmless from any and all liability that we may incur therefor. Upon EarDish’s termination of your use of the Service, EarDish may delete any of your User Materials available on or through the Service and terminate your access to your User Materials if those materials remain on the Service, without any liability to you.</p>

    <p><strong>16.2 TERMINATION BY USER.</strong>  You are free to terminate your use of the Service at any time. You can simply choose to stop visiting or using any aspect of the Service. If you wish to terminate your account on the Service, you may do so by e-mail to <a href="mailto:help@EarDish.com">help@EarDish.com</a> or using any other account termination functionality that may be offered through the Service. For example, we may develop a functionality that permits you to click on a termination button on your profile page on the Website. The deletion of your account will not, however, remove all of your User Materials from the Service unless you also make a specific election to remove your User Materials from the Service. Although we give you the option to delete all of your User Materials from the Service, you are free to keep previously uploaded or posted User Materials on the Service for an unlimited period of time, subject to a change to these Terms. If you do choose to keep User Materials on the Service following termination, these Terms will continue to apply in full force and effect for so long as such materials are available on or through the Service.</p> 

    <p>Notwithstanding Section 16.2, you hereby grant EarDish the right to retain all User Materials on EarDish’s servers for a period of not more than 30 days following a request to terminate a user account and/or delete User Materials from the Service so that you can change your mind and not feel as though you made a big mistake or in the event two or more individuals having administrative rights to a user account on the Service (e.g., a band profile) cannot agree on whether to terminate an account on the Service and/or remove all User Materials from the Service. In the event that there is a request to terminate a user account and/or delete User Materials from a user account for which more than one person has administrative rights for such account, an e-mail notice will be sent to all users having administrative rights for such account notifying them of the request of at least one administrative user to terminate the account and/or delete all User Materials associated with such account. All other administrative users shall thereafter have 30 days within which to object to the request to terminate such account and/or delete User Materials. </p>

    <p>If no action is taken by another user, holding administrative rights to an account within such 30-day period, the account shall be terminated and all User Materials will be deleted from the Service unless an election is made pursuant to Section 16.2 to retain User Materials on the Service notwithstanding the termination of a user account. If, however, any user having administrative rights for such account objects to the termination of such account and/or the deletion of User Materials within the 30-day notice period, then such account shall not be terminated and the users holding administrative rights should resolve amongst themselves the question of whether a user account should be terminated and/or User Materials deleted from the Service. In the absence of an agreement among users holding administrative rights to the same account, the user account shall remain active and all User Materials shall remain on the Service absent an order from a court of competent jurisdiction to the contrary. A user should therefore be careful before giving others administrative rights to an account.</p>

    <p><strong>17.0 NOTICE AND PROCEDURE FOR MAKING CLAIMS OF COPYRIGHT OR OTHER INTELLECTUAL PROPERTY INFRINGEMENTS.</strong>  EarDish respects the intellectual property of others and takes the protection of copyrights and all other intellectual property very seriously, and we ask our users to do the same. Infringing activity will not be tolerated on or through the Service.  EarDish’s intellectual property policy is to:</p>

    <p>a)  Remove material that EarDish believes in good faith, upon notice from an intellectual property owner or their agent, is infringing the intellectual property of a third party by being made available through the Service, and </p>

    <p>b)  Remove any User Content posted to the Service by &quot;<strong>repeat infringers.</strong>&quot; </p>
    
    <p>EarDish considers a &quot;<strong>repeat infringer</strong>&quot; to be any user that has uploaded User Content to the Service and for whom EarDish has received more than two takedown notices compliant with the provisions of 17 U.S.C. § 512(c) with respect to such User Content. EarDish has discretion, however, to terminate the account of any user after receipt of a single notification of claimed infringement or upon EarDish’s own determination.</p>

    <p><strong>17.1 PROCEDURE FOR REPORTING CLAIMED INFRINGEMENT.</strong>  If you believe that any content made available on or through the Service has been Used or exploited in a manner that infringes an intellectual property right you own or control, then please promptly send a &quot;<strong>Notification of Claimed Infringement</strong>&quot; containing the following information to the Designated Agent identified below. Your communication must include substantially the following:</p>

    <p>a)  A physical or electronic signature of a person authorized to act on behalf of the owner of the work(s) that has/have been allegedly infringed;</p>

    <p>b)  Identification of works or materials being infringed, or, if multiple works are covered by a single notification, a representative list of such works;</p>

    <p>c)  Identification of the specific material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit EarDish to locate the material;</p>

    <p>d)  Information reasonably sufficient to permit EarDish to contact you, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted;</p>

    <p>e)  A statement that you have a good faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>

    <p>f)  A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>

    <p>g)  You should consult with your own lawyer and/or see 17 U.S.C. § 512 to confirm your obligations to provide a valid notice of claimed infringement.</p>

    <p><strong>17.2 DESIGNATED AGENT CONTACT INFORMATION.</strong>  EarDish’s Designated Agent for notices of claimed infringement can be contacted at:

    <p style="float:left;clear:none;">VIA EMAIL:</p>
    <p style="float:left;clear:none;"><a href="mailto:copyright@EarDish.com">copyright@EarDish.com</a></p>
    <p style="float:left;clear:left;">VIA U.S. MAIL:</p>
    <p style="float:left;clear:none;">
      PAUL M. LEIGHTON<br/>
      <strong>EARDISH - INFRINGEMENT DEPT</strong><br/>
      3726 LAUREL CANYON BLVD.<br/>
      STUDIO CITY, CA 91604
    </p>
    <p style="clear:both;width:100%;"></p>

    <p><strong>17.3 COUNTER NOTIFICATION.</strong>  If you receive a notification from EarDish that material made available by you on or through the Service has been the subject of a Notification of Claimed Infringement, then you will have the right to provide EarDish with what is called a &quot;Counter Notification.&quot; To be effective, a Counter Notification must be in writing, provided to EarDish’s Designated Agent through one of the methods identified in Section 17.1, and include substantially the following information:</p>

    <p>a)  A physical or electronic signature of the subscriber;</p>

    <p>b)  Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</p>

    <p>c)  A statement under penalty of perjury that the subscriber has a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and</p>

    <p>d)  The subscriber’s name, address, and telephone number, and a statement that the subscriber consents to the jurisdiction of Federal District Court for the judicial district in which the address is located, or if the subscriber’s address is outside of the United States, for any judicial district in which EarDish may be found, and that the subscriber will accept service of process from the person who provided notification under Section 18.3 above or an agent of such person.</p>

    <p><strong>A party submitting a Counter Notification should consult a lawyer or see 17 U.S.C. § 512 to confirm the party’s obligations to provide a valid counter notification under the Copyright Act.</strong></p>

    <p><strong>17.4 FALSE NOTIFICATIONS OF CLAIMED INFRINGEMENT OR COUNTER NOTIFICTIONS.</strong>  The Copyright Act provides that:  Any person who knowingly materially misrepresents under [Section 512 of the Copyright Act (17 U.S.C. § 512)] (1) that material or activity is infringing, or (2) that material or activity was removed or disabled by mistake or misidentification, shall be liable for any damages, including costs and attorneys’ fees, incurred by the alleged infringer, by any copyright owner or copyright owner’s authorized licensee, or by a service provider, who is injured by such misrepresentation, as the result of [EarDish] relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing, or in replacing the removed material or ceasing to disable access to it.  17 U.S.C. § 512(f). EarDish reserves the right to seek damages from any party that submits a notification of claimed infringement or counter notification in violation of the law. For the avoidance of doubt, only notices submitted under the Digital Millennium Copyright Act and the procedures set forth in this Section 17 should be sent to the Designated Agent at <a href="mailto:copyright@EarDish.com">copyright@EarDish.com</a> or to the postal address identified above. Any other comments, compliments, complaints or suggestions about EarDish, the operation of the Service or any other matter should be sent to <a href="mailto:help@EarDish.com">help@EarDish.com</a>.</p>

    <p><strong>18.0 PRIVACY GOVERNS TERMS OF SERVICE.</strong>  Use of these Services are governed by EarDish’s Privacy Policy, which is hereby incorporated into these Terms by reference.</p>

    <p><strong>19.0 JURISDICTIONAL INDEMNIFICATION.</strong>  The website and the Service are controlled and operated by EarDish from its offices within the State of California. EarDish makes no representation that materials on the Site or through the Service are appropriate or available for use in other locations. Those who choose to access or use the Service from other locations, including from outside the United States of America, do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable. Access to the Service from jurisdictions where the contents or practices of the Service are illegal, unauthorized or penalized is strictly prohibited.</p>

    <p><strong>20.0 DISPUTE RESOLUTION.</strong>  <em>Please read this section carefully. It affects your rights.</em></p>

    <p><strong>20.1 MANDATORY ARBITRATION.</strong>  YOU AND EARDISH AND EACH OF OUR RESPECTIVE SUBSIDIARIES, AFFILIATES, PREDECESSORS IN INTEREST, SUCCESSORS, AND PERMITTED ASSIGNS AGREE TO ARBITRATION (EXCEPT FOR MATTERS THAT MAY BE TAKEN TO SMALL CLAIMS COURT), AS THE EXCLUSIVE FORM OF DISPUTE RESOLUTION EXCEPT AS PROVIDED FOR BELOW, FOR ALL DISPUTES AND CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE. </p>

    <p><strong>20.2 COMMENCING ARBITRATION.</strong>  A party who intends to seek arbitration must first send to the other, by certified mail, a written notice of intent to arbitrate (a &quot;<strong>Notice</strong>&quot;), or, in the absence of a mailing address provided by you to EarDish, to you via any other method available to EarDish, including via e-mail. The Notice to EarDish should be addressed to the <strong>Arbitration Notice Address</strong>: 

    <blockquote>EarDish Corporation<br/>
    3726 Laurel Canyon Blvd.<br/>
    Studio City, CA 91604,<br/>
    Attn: Chief Operating Officer</blockquote>

    <p>The Notice must:</p>

    <ol>
      <li>Describe the nature and basis of the claim or dispute; and</li>
      <li>Set forth the specific relief sought (the &quot;<strong>Demand</strong>&quot;). If you and EarDish do not reach an agreement to resolve the claim within 30 days after the Notice is received, you or EarDish may commence an arbitration proceeding as set forth below or file a claim in small claims court. </li>
    </ol>

    <p><strong>THE ARBITRATION SHALL BE ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION (&quot;<u>AAA</u>&quot;) IN ACCORDANCE WITH ITS COMMERCIAL ARBITRATION RULES AND THE SUPPLEMENTARY PROCEDURES FOR CONSUMER RELATED DISPUTES (THE &quot;<u>Rules</u>&quot;), AS MODIFIED BY THIS AGREEMENT.</strong></p>
    
    <p>The Rules and AAA forms are available online at www.adr.org or by calling the AAA at 1-800-778-7879, or by writing to the Notice Address. If you are required to pay a filing fee to commence an arbitration against EarDish, then EarDish will promptly reimburse you for your confirmed payment of the filing fee upon EarDish’s receipt of Notice at the Arbitration Notice Address that you have commenced arbitration along with a receipt evidencing payment of the filing fee, unless your Demand is equal to or greater than $1,000, in which case you are solely responsible for the payment of the filing fee.</p>

    <p><strong>20.3 ARBITRATION PROCEEDING.</strong> The arbitration shall be conducted in the English language. A single independent and impartial arbitrator shall be appointed pursuant to the Rules, as modified herein. You and EarDish agree to comply with the following rules, which are intended to streamline the dispute resolution process and reduce the costs and burdens on the parties: </p>

    <p>(i) The arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner to be chosen by the party initiating the arbitration; </p>

    <p>(ii)  The arbitration shall not require any personal appearance by the parties or witnesses unless otherwise mutually agreed in writing by the parties; and</p>

    <p>(iii) Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.</p>

    <p><strong>20.4 NO CLASS ACTIONS.</strong>  <em>YOU AND EARDISH AGREE THAT YOU AND EARDISH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. FURTHER, YOU AGREE THAT THE ARBITRATOR MAY NOT CONSOLIDATE PROCEEDINGS OF MORE THAN ONE PERSON’S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND THAT IF THIS SPECIFIC PROVISO IS FOUND TO BE UNENFORCEABLE, THEN THE ENTIRETY OF THIS MANDATORY ARBITRATION SECTION SHALL BE NULL AND VOID.</em></p>

    <p><strong>20.5 DECISION OF THE ARBITRATOR.</strong> Barring extraordinary circumstances, the arbitrator shall issue his or her decision within 120 days from the date the arbitrator is appointed. The arbitrator may extend this time limit for an additional 30 days in the interests of justice. All arbitration proceedings shall be closed to the public and confidential and all records relating thereto shall be permanently sealed, except as necessary to obtain court confirmation of the arbitration award. The award of the arbitrator shall be in writing and shall include a statement setting forth the reasons for the disposition of any claim. The arbitrator shall apply the laws of the State of California in conducting the arbitration. You acknowledge that these terms and your use of the Service evidences a transaction involving interstate commerce. The United States Federal Arbitration Act shall govern the interpretation, enforcement, and proceedings pursuant to the Mandatory Arbitration clause in these Terms.</p>

    <p><strong>These Terms and your use of the Service shall be governed by the substantive laws of the State of California</strong> without reference to its choice or conflicts of law principles. Only if the Mandatory Arbitration clause is deemed to be null and void, then all disputes arising between you and EarDish under these Terms shall be subject to the exclusive jurisdiction of the state and federal courts located in Los Angeles County, California, and you and EarDish hereby submit to the personal jurisdiction and venue of these courts.</p>

    <p><strong>20.6 EQUITABLE RELIEF.</strong>  The foregoing provisions of this Dispute Resolution section do not apply to any claim in which EarDish seeks equitable relief of any kind. You acknowledge that, in the event of a breach of these Terms by EarDish or any third party, the damage or harm, if any, caused to you will not entitle you to seek injunctive or other equitable relief against EarDish, including with respect to any User Materials, and your only remedy shall be for monetary damages, subject to the limitations of liability set forth in these Terms.</p>

    <p><strong>20.7 CLAIMS.</strong> You and EarDish agree that, notwithstanding any other rights the party may have under law or equity, any cause of action arising out of or related to these Terms or the Service, excluding a claim for indemnification, must commence within one year after the cause of action accrues. Otherwise, such cause of action is permanently barred.</p>

    <p><strong>20.8 IMPROPERLY FILED CLAIMS.</strong>  All claims you bring against EarDish must be resolved in accordance with this Dispute Resolution section. All claims filed or brought contrary to this Dispute Resolution section shall be considered improperly filed. Should you file a claim contrary to this Dispute Resolution section, EarDish may recover attorneys' fees and costs up to $5,000, provided that EarDish has notified you in writing of the improperly filed claim, and you have failed to promptly withdraw the claim.</p>

    <blockquote><strong>MISCELLANEOUS</strong></blockquote>

    <p><strong>21.0 WAIVER.</strong> A provision of these Terms may be waived only by a written instrument executed by the party entitled to the benefit of such provision. The failure of EarDish to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision.</p>

    <p><strong>22.0 SEVERABILITY.</strong>  If any provision of these Terms shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.</p> 

    <p><strong>23.0 ASSIGNMENT.</strong>  These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by EarDish without restriction. Any assignment attempted or made by you in violation of these Terms shall be void. These Terms will be binding upon and inure to the benefit of the parties hereto, and permitted successors and assigns.</p>

    <p><strong>24.0 NO AGENCY. </strong> You agree that no joint venture, partnership, employment, or agency relationship exists between you and EarDish as a result of these Terms or use of the Service. You further acknowledge that by submitting user content, no confidential, fiduciary, contractually implied or other relationship is created between you and EarDish other than pursuant to these Terms.</p>

    <p><strong>25.0 SURVIVAL.</strong> If any provision of these Terms are found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that ALL surviving Terms will otherwise remain in full force and effect and enforceable.</p>

    <p><strong>26.0 HEADINGS. </strong> The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and shall not be deemed to limit or affect any of the provisions hereof.</p>

    <p><strong>27.0 ENTIRE AGREEMENT. </strong>This is the entire agreement between you and EarDish relating to the subject matter herein and supersedes all previous communications, representations, understandings and agreements, either oral or written, between the parties with respect to said subject matter. These Terms shall not be modified except in writing, signed by both parties, or by a change to these Terms made by EarDish as authorized in these Terms.</p>

    <p><strong>28.0 DISCLOSURES.</strong> The services hereunder are offered by:</p>

    <blockquote><strong>EarDish Corporation</strong><br/>
    3726 Laurel Canyon Blvd.<br/>
    Studio City, CA 91604</blockquote>
    
    <p>You may contact us at the address above or by emailing us at <a href="mailto:help@EarDish.com">help@EarDish.com</a>.  If you are a California resident, you may have these Terms mailed to you electronically by sending a letter to the foregoing address with your electronic mail address and a request for these Terms.</p>

  </div>
</div>
